[auth]
  default_new_user_role = "restrictedcontrol"
  backend = "ldap"
  samlEnabled = false
  samlLoginText = ""
  scimEnabled = false
  managedPasswordDisabled = false
  managedPasswordFallbackUser = ""
  wellKnownOpenIdConfig = ""
  externalOpenIdProviderClientId = ""
  [auth.sessions]
    lifetime_minutes = 60
    renewal_threshold_minutes = 20
    per_user_limit = 10
    store_token_per_session = false
  [auth.saml]
    idpMetadataURL = ""
    spHost = ""
    rootCerts = ""
    tlsSkipVerify = false
  [auth.scim]
    token = ""
    orgName = ""

[scheduling_configuration]
  enable_admin_ucp_scheduling = true
  default_node_orchestrator = "swarm"

[tracking_configuration]
  disable_usageinfo = true
  disable_tracking = true
  anonymize_tracking = false
  cluster_label = ""

[trust_configuration]
  require_content_trust = false
  require_signature_from = []
  allow_repos = []

[log_configuration]
  level = "INFO"

[audit_log_configuration]
  level = ""
  support_dump_include_audit_logs = false

[license_configuration]
  auto_refresh = false

[pki]
  client_ca_bundle = ""

[user_workload_defaults]

[cluster_config]
  controller_port = 443
  kube_apiserver_port = 6443
  swarm_port = 2376
  swarm_strategy = "spread"
  kv_timeout = 5000
  kv_snapshot_count = 20000
  profiling_enabled = false
  swarm_polling_disabled = false
  hide_swarm_ui = false
  image_scan_aggregation_enabled = false
  external_service_lb = ""
  metrics_retention_time = "24h"
  metrics_scrape_interval = "1m"
  rethinkdb_cache_size = "1GB"
  exclude_server_identity_headers = false
  cloud_provider = ""
  iscsi_enabled = false
  iscsiadm_path = ""
  iscsidb_path = ""
  storage_expt_enabled = false
  cni_installer_url = ""
  pod_cidr = "10.230.0.0/16"
  calico_ip_auto_method = ""
  calico_mtu = "1480"
  calico_vxlan = true
  vxlan_vni = 10000
  calico_vxlan_mtu = "1450"
  calico_vxlan_port = "4789"
  ipip_mtu = "1480"
  unmanaged_cni = false
  service_cluster_ip_range = "10.231.0.0/16"
  nodeport_range = "32768-35535"
  azure_ip_count = ""
  secure_overlay = false
  kms_enabled = false
  kms_name = ""
  kms_endpoint = ""
  kms_cachesize = 0
  local_volume_collection_mapping = false
  manager_kube_reserved_resources = "cpu=250m,memory=2Gi,ephemeral-storage=4Gi"
  worker_kube_reserved_resources = "cpu=50m,memory=300Mi,ephemeral-storage=500Mi"
  kubelet_max_pods = 110
  windows_gmsa = false
  cluster_name = ""
  pre_logon_message = ""
  networks_quota_per_collection = 0
  [cluster_config.service_mesh]
    enabled = false
    ingress_num_replicas = 2
    ingress_enable_lb = false
    ingress_preserve_client_ip = false

    [[cluster_config.service_mesh.ingress_exposed_ports]]
      name = "http2"
      port = 80
      target_port = 0
      node_port = 33000

    [[cluster_config.service_mesh.ingress_exposed_ports]]
      name = "https"
      port = 443
      target_port = 0
      node_port = 33001

    [[cluster_config.service_mesh.ingress_exposed_ports]]
      name = "tcp"
      port = 31400
      target_port = 0
      node_port = 33002

    [[cluster_config.service_mesh.ingress_exposed_ports]]
      name = "https-prometheus"
      port = 15030
      target_port = 0
      node_port = 0

    [[cluster_config.service_mesh.ingress_exposed_ports]]
      name = "tls"
      port = 15443
      target_port = 0
      node_port = 0

    [[cluster_config.service_mesh.ingress_exposed_ports]]
      name = "status-port"
      port = 15020
      target_port = 0
      node_port = 0

    [[cluster_config.service_mesh.ingress_node_toleration]]
      key = "com.docker.ucp.manager"
      value = ""
      operator = "Exists"
      effect = "NoSchedule"
